#pragma once
#include <string>
#include <vector>
#include <memory>
#include <cstdint>
#include "schema/AssetNode.h"

namespace GOW {
    class IGameProfile;
    class IFile;
}

// ── WadAssetName ──────────────────────────────────────────────────────────────
// Parses a FileDesc name from the Ragnarök WAD in the format:
//   PREFIX_baseName_lodIndex_variant---wadIndex.bin
//
// Exemplos:
//   "MG_heroa00_0_gpu---12389"   -> prefix="MG",  base="heroa00",  lod=0, variant="gpu",  wadIndex=12389
//   "ANM_heroa00---10397"        -> prefix="ANM", base="heroa00",  lod=-1, variant="",    wadIndex=10397
//   "autopad---10399"            -> prefix="",    base="autopad",  lod=-1, variant="",    wadIndex=10399
//   "DCClientGUID---13956"       -> prefix="",    base="DCClientGUID", lod=-1, variant="",wadIndex=13956
//   "a41955a3abdbf109_ps_30000207---2447" -> prefix="", base="a41955a3abdbf109", lod=-1, variant="ps_30000207", wadIndex=2447
//
// The wadIndex is the sequential FileDesc index inside the WAD (field after "---").
// It is NOT a hash — just the insertion position used for debug/extraction.
//
// The "---" separator + number is generated by the export tool, not read back by the engine.
struct WadAssetName {
    std::string prefix;     // "MG", "ANM", "PEM", "GOWR_SHADER", "" (empty = no prefix)
    std::string base;       // asset name: "heroa00", "DCClientGUID", "autopad"
    int         lod  = -1;  // LOD index (>= 0 if present), -1 = no LOD
    std::string variant;    // "gpu", "cpu", "ps", "ps_30000207", "" = no variant
    int         wadIndex = -1; // sequential FileDesc index (number after "---")

    // Returns true if the name was successfully parsed from a raw string.
    // The raw field does NOT include the ".bin" extension — pass only the stem.
    static WadAssetName Parse(const std::string& raw);

    // Group key: joins prefix + base to group variants/LODs of the same asset.
    // E.g.: "MG_heroa00_0_gpu" and "MG_heroa00_0_cpu" -> groupKey = "MG|heroa00"
    std::string GroupKey() const {
        return prefix.empty() ? base : (prefix + "|" + base);
    }

    // Reconstructs the canonical name without the wadIndex (as the engine sees the asset).
    std::string CanonicalName() const;

    // Returns true if this is a GPU variant (needs lodpack for vertex data).
    bool IsGpuVariant()  const { return variant == "gpu"; }
    // Returns true if this is a PS4/PS5 shader (name is a hex hash).
    bool IsShader()      const { return variant.find("ps") != std::string::npos ||
                                        variant.find("vs") != std::string::npos; }
    // Returns true if this is an internal entry with no asset semantics (autopad, PopHeap, etc.).
    bool IsInternal()    const { return prefix.empty() && lod < 0 && variant.empty(); }
};

// Semantic role of a single FileDesc entry inside a Ragnarok WAD.
// Assigned by WadNodeBuilder::Pass1_Classify() from name patterns + size.
enum class WadEntryRole {
    // Structural / Meta
    WadIdentity,        // WAD_R_*
    SharedWadRef,       // *X_R_* entries
    Sentinel,           // PopHeap, autopad

    // Shaders
    ShaderContainer,    // 0xHASH entries
    ShaderVertex,       // name_vs_FLAGS or HASH_vs_FLAGS
    ShaderPixel,        // HASH_ps_FLAGS

    // Core Assets
    AnimClip,           // ANM_*
    TextureGpu,         // TX_* with large size (GPU data)
    TextureCpu,         // TX_* with small size (CPU descriptor)
    Material,           // MAT_HASH with size > 0
    MaterialRef,        // MAT_HASH with size == 0
    LodBinding,         // N_0_M entries
    MeshGpu,            // MG_*_gpu
    MeshDefn,           // MESH_* or MG_*
    Model,              // MDL_*

    // Game Objects
    GameObjectProto,    // goProto*
    GameObjectInst,     // go*
    GameObjectOverride, // go*_overrideInst

    // Audio
    SoundEmitter,       // SEMW_*

    // Particle FX
    ClientGuid,         // DCClientGUID
    ParticleEmitter,    // PEM_emit_*
    ParticleSystem,     // PTC_part_*

    // Synthetic (builder-generated virtual nodes)
    TexturePair,
    ShaderGroup,
    FxGroup,
    ManifestBlock,
    ShaderBlock,
    AssetBlock,
    ParticleBlock,

    Unknown
};

// Functional block that an entry belongs to.
enum class WadBlock {
    Manifest,
    Shaders,
    Assets,
    Particles,
    Unknown
};

#include "types/TypeId.h"
#include "types/GameVersion.h"

struct ParsedEntry {
    std::string           name;
    std::string           wadName;
    WadAssetName          parsedName; // decomposed name via WadAssetName::Parse
    uint32_t              size = 0;
    uint32_t              offset = 0;
    uint64_t              hash = 0;
    
    // Schema type string (e.g. "GOW2_MDL", "GOW1_TXR")
    std::string           schemaType; 
    
    // Compiled type identifier
    GOW::TypeId           typeId = GOW::TypeId::Unknown;
    
    // Child nodes for UI tree
    std::vector<ParsedEntry> children;
    
    // Loaded data (on demand)
    std::shared_ptr<GOW::AssetNode> assetNode;

    // Semantic classification — set by WadNodeBuilder
    WadEntryRole  role        = WadEntryRole::Unknown;
    WadBlock      block       = WadBlock::Unknown;
    std::string   displayName;   // human-friendly name (falls back to name if empty)
};

// Bridge: converts TypeId to legacy schema string for UI display.
inline std::string TypeIdToSchemaString(GOW::GameVersion ver, GOW::TypeId id) {
    if (ver == GOW::GameVersion::GOW1) {
        switch (id) {
            case GOW::TypeId::Model:    return "GOW1_MDL";
            case GOW::TypeId::Mesh:     return "GOW1_MESH";
            case GOW::TypeId::Material: return "GOW1_MAT";
            case GOW::TypeId::Texture:  return "GOW1_TXR";
            case GOW::TypeId::Animation:return "GOW1_ANM";
            default: break;
        }
    } else if (ver == GOW::GameVersion::GOW2) {
        switch (id) {
            case GOW::TypeId::Instance: return "GOW2_SERVER_INSTANCE";
            case GOW::TypeId::Object:   return "GOW2_OBJ";
            case GOW::TypeId::Model:    return "GOW2_MDL";
            case GOW::TypeId::Mesh:     return "GOW2_MESH";
            case GOW::TypeId::Material: return "GOW2_MAT";
            case GOW::TypeId::Texture:  return "GOW2_TXR";
            case GOW::TypeId::GfxData:  return "GOW2_GFX";
            case GOW::TypeId::PalData:  return "GOW2_PAL";
            case GOW::TypeId::Animation:return "GOW2_ANM";
            case GOW::TypeId::Script:   return "GOW2_SCP";
            case GOW::TypeId::Light:    return "GOW2_LGT";
            case GOW::TypeId::Sound:    return "GOW2_SFX"; // or VAG/VPK depending on extension
            case GOW::TypeId::EntityCount: return "GOW2_ENTITY_COUNT";
            case GOW::TypeId::GroupStart:  return "GOW2_GROUP_START";
            case GOW::TypeId::GroupEnd:    return "GOW2_GROUP_END";
            case GOW::TypeId::WadFile:     return "GOW2_WAD_FILE";
            default: break;
        }
    }
    return "";
}

struct OpenWad {
    std::string                        filename;
    std::string                        fullPath;
    std::shared_ptr<GOW::IGameProfile> profile;
    std::shared_ptr<GOW::IFile>        fileSource;
    std::vector<ParsedEntry>           entries;
};
